name: Update user permissions on EC2
on:
  push:
    branches:
      - master
    paths:
      - 'Devops-Automation/Ec2-Access-Control/lambda-payload.json'
jobs:
  UpdatePermissions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Assume AWS IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::532968567499:role/Lambda-Action-Role
          aws-region: us-east-2
      - name: Invoke lambda with new Permissions
        run: aws lambda invoke --function-name OhLambdaLdapAccessConfig --cli-read-timeout 0 --payload fileb:///home/runner/work/aws-code/aws-code/Devops-Automation/Ec2-Access-Control/lambda-payload.json --region us-east-2 outfile.txt
